### ISSUE TITLE
A lot of errors

### ISSUE THREAD

**Issue by ghost** [AlexWaveDiver/TranslaTale-NG#1]
I forked the project so I could see what needed to be worked on (so I could fix them in my free time) in my Codacy dashboard, and saw this:
![screenshot 2017-12-07 at 3 34 04 pm](https://user-images.githubusercontent.com/23317696/33737444-1b402060-db64-11e7-9b22-77080867a691.png)
Just wanted to let you know...

**Comment by AlexWaveDiver** [comment]
It's very barebones and still WIP, lacking basic functionalities :(
